---
title: Take Tonight
timezone: UTC
collections:
  posts:
    title: Posts
    output: false
  projects:
    title: Projects
    output: false
  uploads:
    title: Uploads
    output: true
email: scott@enkota.com
description: Rock band from Glasgow, Scotland
baseurl: ''
url: ''
twitter_username: taketonightband
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
- jekyll-seo-tag
