---
title: Take Tonight
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  webg:
    title: Webg
    output: true
defaults:
- scope:
    path: ''
  values:
    image: "/assets/img/default-card.jpg"
email: contact@taketonight.com
description: Rock band from Glasgow, Scotland
logo: "/assets/img/logo.png"
url: https://taketonight.com
baseurl: ''
favicon: "/assets/img/apple-touch-icon.png"
twitter:
  username: taketonightband
facebook:
  publisher: https://www.facebook.com/taketonight
social:
  links:
  - https://www.facebook.com/taketonight
  - https://twitter.com/taketonightband
  - https://www.youtube.com/c/taketonightofficial
blog_name: Take Tonight News
blog_description: Stay informed with the latest news happening at Take Tonight.
permalink: pretty
markdown: kramdown
exclude:
- node_modules
- gulpfile.js
- vendor
- Gemfile
- Gemfile.lock
- gulpfile.js
- package.json
- "-README.md"
gems:
- jekyll-seo-tag
- jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed
pagination:
  enabled: true
  debug: false
  collection: posts
  per_page: 5
  permalink: "/page/:num/"
  title: ":title - page :num"
  limit: 0
  sort_field: date
  sort_reverse: true
  category: posts
  tag: ''
  locale: ''
  trail:
    before: 2
    after: 2
